baseURL = 'https://alphasciencebg.github.io/website/'
title = 'AlphaScience'
theme = 'spectral'
languageCode = 'en'
defaultContentLanguage = "en"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
fancytitle = '<img height="128" src="assets/images/logo.jpg" alt="Logo"/><br />AlphaScience'
copyright = "Alpha Man"
description = 'Driving better decisions through artificial intelligence and machine learning'
startbuttonLink = "#contact"
startbuttonText = "Ask a question"

# ### First section ###
# [languages.en.one]
[params.one]
enable = true
title = 'AlphaScience – the best for your business'
body = '''
We are a strong team with over thirty years of experience in various branches of industry with special emphasis on <b>machine
learning</b> and <b>data science applications</b> for the financial and energy sectors. 
'''

[[params.one.icon]]
icon = "solid fa-gear"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "solid fa-globe"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "solid fa-bolt"
style = "3"
label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "assets/images/energy/forecasting-engl-mls-emft.jpg"
# img_alt = "blurry background: white/grey"
title = 'Time series forecasting <br />and anomaly detection'
body = 'Real time data quality and model monitoring for different domains with customized analytics'

[[params.two.section]]
img = "assets/images/cloud.png"
title = 'Scalable cloud solutions<br />and model development'
body = 'Iterative and continuous model and data pipeline designs on scalable, state-of-the-art infrastructure'

[[params.two.section]]
img = "assets/images/BG.png"
title = 'Magna primis lobortis<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[params.three]
enable = true
title = 'Holistic Approach'
body = '''
Combine ML + domain partners for full-stack impact
'''

[[params.three.feature]]
icon = "fa-paper-plane"
title = "Speed to Value"
body = "Pre-built modules for common energy use cases"

[[params.three.feature]]
icon = "solid fa-laptop"
title = "Transparency"
body = "Explainable AI for regulatory compliance"

[[params.three.feature]]
icon = "solid fa-code"
title = "Domain Knowledge"
body = "Energy markets, grid dynamics, regulatory frameworks"

[[params.three.feature]]
icon = "solid fa-headphones-alt"
title = "Proven Impact"
body = "Reduced forecasting errors by 20 – 30 % for clients"

# [[params.three.feature]]
# icon = "fa-heart"
# title = "Some latin text"
# body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."
#
# [[params.three.feature]]
# icon = "fa-flag"
# title = "Nothing important"
# body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = false
title = "Arcue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
phone = "+359 (0) 888 681 896"
address = "Lavele 19, Sofia, Bulgaria"
email = "hgoumnerov@tuta.io"
subject = "Inquiry from website"
formspree_form_id = "example_invalid"

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = ""
youtube = ""
instagram = ""
dribble = ""

# [languages.en.contact]
# enable = true
# title = "Contact"
# phone = "+359 XXX XXX XXX"
# email = "contact@alphascience.bg"
# body = 'Contact us for questions and orders. Please remember to mention your address and payment details in your order.'
# address = "Alpha Man<br />Alphaland<br />1234 Alpha<br />ALPHANISTAN"
# subject = "New inquiry from alphascience.bg"
# formspree_form_id = "mjvzpzyw"
# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"

[languages.es]
weight = 10
languageName = "Español"
